### ISSUE TITLE
Difference between `CAST()` and `::` on page 56 need more clarification

### ISSUE THREAD

**Issue by vasili111** [anthonydb/practical-sql-2#10]
If I run:

```
SELECT timestamp_column, CAST(timestamp_column AS varchar(10))
FROM date_time_types;
```

I am receiving as output original column and modified column.

If I run:
```
SELECT timestamp_column::varchar(10)
FROM date_time_types;
```
I am receiving as output only modifying column. So, it seems that those two examples are not identical. I think text needs to clarify why the output of those two examples are different.

**Comment by anthonydb** [comment]
In my opinion, this is not an issue as the point of the exercise should be clear -- that `CAST()` and the `::` syntax perform the same operation. But I'll keep this in mind for future updates.
