### ISSUE TITLE
Incorrect # of listing on p.240 and p.241 

### ISSUE THREAD

**Issue by vasili111** [anthonydb/practical-sql-2#13]
In section "Tabulating City Temperature Readings" on p.240 (bottom) and p.241 you are referring to "Listing 13-18" as to the example of crostab but the listing 13-18 is for creating table and loading data. I think you meant instead "Listing 13-17".

**Comment by anthonydb** [comment]
Thanks for flagging. Noted in FAQ and will be corrected in an upcoming printing.
