### ISSUE TITLE
page-297 Listing 15-16// ERROR:  

### ISSUE THREAD

**Issue by abhi11111111-255** [anthonydb/practical-sql-2#16]
ERROR:  contains: Operation on mixed SRID geometries (MultiPolygon, 0) != (Point, 4269) 
I am getting this error for listing 15-16.
Shapfile was loaded successfully
I am using windows 11 machine.

**Comment by anthonydb** [comment]
Hi. I'm not able to reproduce this error. I did a fresh load of the shapefile from this repo, and the query ran fine. Please drop the table and re-run the import making sure you followed all steps, including specifying the correct SRID (4269).

**Comment by abhi11111111-255** [comment]
*SELECT UpdateGeometrySRID('public', 'us_counties_2019_shp', 'geom', 4269);*

Sir
After running the above cmd *issue got result.*
Thanks for such a nice book.

**Comment by anthonydb** [comment]
Glad that worked. For others, note the the SRID should be set during shapefile load if using the Windows shapefile installer or via the shp2pgsql command line tool.
