### ISSUE TITLE
Charpter 7 Issue on Listing 7-18: Performing math on joined Census population estimates tables

### ISSUE THREAD

**Issue by lucasefontes** [anthonydb/practical-sql-2#18]
Having trouble with data, code, or exercises in Practical SQL, 2nd Edition? I'm glad to help. Please answer these questions, and I'll typically reply within one to two business days.

Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

### General
Please answer all of these as they're essential for troubleshooting.

**What's your operating system (e.g. Windows 10, macOS Monterey, Ubuntu, etc.)?**

Windows

**Did you install PostgreSQL, PostGIS and pgAdmin according to the steps in Chapter 1? If not, please describe your installation (e.g., using RDS on Amazon Web Services).**

Yes

**Which versions of PostgreSQL and pgAdmin 4 are you using? If you aren't sure, for PostgreSQL run the SQL command `SELECT version();` and for pgAdmin 4, navigate to "About pgAdmin 4" under the "Help" menu.**

PostgreSQL 16, pgAdmin 7.2

**Did you download the book's code examples and data from GitHub using the directions in Chapter 1? If not, please describe how you loaded the material on your computer.**

Yes

### Issue or Question

**Chapter, page and code listing number:**

Chapter 7, page 112 and 113.

**Describe the issue or your question:**

in the table us_counties_pop_est_2010 you are creating 2 columns with wrong data type, state_fips and county_fips as text.
When you try to run the SELECT from page, you get this error:

_______________________________________

ERROR:  operator does not exist: integer = text
LINE 10: ON c2019.state_fips = c2010.state_fips
                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. 

SQL state: 42883
Character: 444

_______________________________________

Changing the last part of the SELECTION to CAST to integer, makes it to work: 

FROM us_counties_pop_est_2019 AS c2019
	JOIN us_counties_pop_est_2010 AS c2010
ON c2019.state_fips = c2010.state_fips::int
	AND c2019.county_fips = c2010.county_fips::int
ORDER BY pct_change DESC;

**Comment by anthonydb** [comment]
Hi, @lucasefontes,

I cannot replicate that error. 

In pgAdmin, please run the following query and post a screen grab here of the result including the column headers.

```
SELECT * FROM us_counties_pop_est_2019 LIMIT 10;
```

**Comment by lucasefontes** [comment]
Hey @anthonydb,

I think you got it, for some reason my us_counties_pop_est_2019 table has both columns set as integers and why I saw the issue.

![image](https://github.com/anthonydb/practical-sql-2/assets/62809932/e70a4317-adbf-4710-a6aa-5807934afbd0)

I should have gone back to chapter 5 before making this post, I actually did it now and see both columns are also created as text, I may have created them as integers and have not realized.

You can consider this closed, sorry to bother.

**Comment by anthonydb** [comment]
@lucasefontes 
Glad we figured it out. The reason the FIPS columns are set as text is because some of the FIPS codes have leading zeros, such as `01` for Alabama. Using an integer data type strips out the leading zero.
