### ISSUE TITLE
Chapter-5, Median Script is not working in Postgres 14

### ISSUE THREAD

**Issue by Rikixn** [anthonydb/practical-sql-2#2]
I tried to run that median script in chapter 5 which gives me this error now :

ERROR:  function array_append(anyarray, anyelement) does not exist
SQL state: 42883

I tried to search for a solution but people mentioned this script won't work on postgres 14.
So do i have to downgrade to version 13 or is there some alternate method to get this median script working or can i just skip this and go around working with percentile cont. funciton ? Or maybe m i doing something wrong here ?

**Comment by anthonydb** [comment]
Hi, @Rikixn,

You've posted this question in the repo for the 2nd Edition of Practical SQL, which does not include a user-defined `median()` function. I removed that function from the 2nd Edition for the reason you cite -- it does not work beginning with PostgreSQL 14.

The preferred solution is to use `percentile_cont()` to find the 50th percentile.

I will add a note to the code for the 1st Edition as I know that version of the book is still available in libraries and in used copies.

**Comment by Rikixn** [comment]
Thanks for replying.  I will continue with percentile_cont() function than and your book is great like literally its helping me out to learn SQL the right way. Also shall i prefer 2nd edition over this one ? i mean if there are useful updates in that one can switch to it.

**Comment by anthonydb** [comment]
@Rikixn, 

The 2nd Edition of the book is expanded and updated, and I would recommend using it instead of the 1st Edition if possible.
