### ISSUE TITLE
Chapter 5, page 69, listing 5-4: Code download does not match book 

### ISSUE THREAD

**Issue by 0sergio-hash** [anthonydb/practical-sql-2#20]
In the book, start_date is created as the date data type, but in the .sql file for the chapter, it comes up as text type.

```sql
-- Listing 5-4: Creating a table to track supervisor salaries

CREATE TABLE supervisor_salaries (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    town text,
    county text,
    supervisor text,
    start_date text,
    salary numeric(10,2),
    benefits numeric(10,2)
);

```

**Comment by anthonydb** [comment]
@0sergio-hash: Thanks for flagging that! I've corrected via https://github.com/anthonydb/practical-sql-2/commit/edf4b3955269d1d85699d0f973ef64f4a3422dff
