### ISSUE TITLE
Wrong description in the comments of Try_It_Yourself.sql

### ISSUE THREAD

**Issue by krave1986** [anthonydb/practical-sql-2#21]
https://github.com/anthonydb/practical-sql-2/blob/83f6884ac892d623e8385e947f0a6fd65c5d9e57/Try_It_Yourself/Try_It_Yourself.sql#L680

The correct description should be:
> The r value of pct_masters_higher and median_hh_income is about .60

**Comment by anthonydb** [comment]
Thanks! Fixed via https://github.com/anthonydb/practical-sql-2/commit/5f6b5e033125259f261c40d97cb2c8c3b8b4a61c
