### ISSUE TITLE
Chapter 15: Broken link

### ISSUE THREAD

**Issue by krave1986** [anthonydb/practical-sql-2#22]
I can not open this link https://docs.geotools.org/stable/javadocs/org/opengis/referencing/doc-files/WKT.html

It seems that the doc is not available on this page anymore.

**Comment by anthonydb** [comment]
@krave1986 Thanks for flagging. Looks like it has moved to [https://docs.geotools.org/stable/javadocs/org/geotools/api/referencing/doc-files/WKT.html](https://docs.geotools.org/stable/javadocs/org/geotools/api/referencing/doc-files/WKT.html). I've noted the change in the [FAQ](https://github.com/anthonydb/practical-sql-2/blob/main/faq-updates-errata.md)
