### ISSUE TITLE
Chapter 20: Which are the the resources for advanced statistics.

### ISSUE THREAD

**Issue by krave1986** [anthonydb/practical-sql-2#23]
There is a note in Chapter 20 section of Identify Key Indicators and Trends over Time.
It says that See the appendix for PostgreSQL resources for advanced statistics.

I jumped to the appendix but not able to find out which resources are about advanced statistics.
Did I miss anything?

Thank you!

**Comment by anthonydb** [comment]
Hi, please note the MADlib Apache library listed on page 409. https://madlib.apache.org/

**Comment by krave1986** [comment]
Thank you!
