### ISSUE TITLE
Encountering Error Exporting All Data  Chapter 5: Pg. 72

### ISSUE THREAD

**Issue by MerakiMK** [anthonydb/practical-sql-2#24]
**What's your operating system (e.g. Windows 10, macOS Monterey, Ubuntu, etc.)?**

Windows 10
**Did you install PostgreSQL, PostGIS and pgAdmin according to the steps in Chapter 1? If not, please describe your installation (e.g., using RDS on Amazon Web Services).**

Yes
**Which versions of PostgreSQL and pgAdmin 4 are you using? If you aren't sure, for PostgreSQL run the SQL command `SELECT version();` and for pgAdmin 4, navigate to "About pgAdmin 4" under the "Help" menu.**

PostgreSql 16.2 pg admin version 8.2
**Did you download the book's code examples and data from GitHub using the directions in Chapter 1? If not, please describe how you loaded the material on your computer.**

Yes
### Issue or Question
Issue
**Chapter, page and code listing number:**
5, 72, listing 5-8

**Describe the issue or your question:**
Whenever I try to export the table to the .txt file it comes up with this error. I have been stuck on this for quite some time and have changed the permissions to "everyone" on the file too but that also did not work.

**Please paste the code and error message here. It's OK to alter identifying info such as a folder name**

COPY us_counties_pop_est_2019
TO 'C:\Users\Admin\Desktop\SQL\us_counties_export.txt'
WITH (FORMAT CSV, HEADER, DELIMITER '|');

ERROR:  could not open file "C:\Users\Admin\Desktop\SQL\us_counties_export.txt" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy. 

SQL state: 42501

**Comment by anthonydb** [comment]
> I have been stuck on this for quite some time and have changed the permissions to "everyone" on the file too

Hi, did you change the permissions for the folder named `SQL`?

**Comment by MerakiMK** [comment]
Thank you it's been solved, it was just my antivirus messing things up with my folder properties. So that's everything I needed, love the book so far.
