### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by 0sergio-hash** [anthonydb/practical-sql-2#26]
https://github.com/anthonydb/practical-sql-2/blob/712cec0d31352e4d5e617da7c8f880fcefb60c28/Chapter_16/Chapter_16.sql#L296

Shouldn't this say "geography" instead of "geometry" ? Or am I misunderstanding something?
Appears the same way in the physical copy of the book

**Comment by anthonydb** [comment]
You are correct! Good eye and thank you. Updated via https://github.com/anthonydb/practical-sql-2/commit/41a9bb7eae8e0ea7cea208f9a60cba611cfddc22 and the physical book will be updated in a future printing.
