### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 0sergio-hash** [anthonydb/practical-sql-2#27]
https://github.com/anthonydb/practical-sql-2/blob/41a9bb7eae8e0ea7cea208f9a60cba611cfddc22/Chapter_18/psql_commands.txt#L69

Quick question! I ended up having to use the meta command to get this to run:
psql -d analysis -U postgres -c "\copy state_regions FROM STDIN WITH (FORMAT CSV, HEADER);" < "C:\Users\...\practical-sql-2-main\Chapter_10\state_regions.csv"

Will either one work ?

Also, do single vs double quotes make a difference here? Book has single quotes around COPY and none around the file path, wasn't sure if they were interchangeable or optional

**Comment by anthonydb** [comment]
Hi, both the meta command `\copy` and using `psql` work for me on Windows and macOS as written in the book. Was one of them not working for you?

Either way, the two commands in Listings 18-7 and 18-8 have the same result -- they import the state_regions.csv file to the table.

For quotes, I followed conventions in the PostgreSQL docs and suggest following that syntax.

**Comment by 0sergio-hash** [comment]
Got you! Thanks for responding. Sorry for making a issue out of it, wasn't sure how else to ask the question.

I pasted the error I had gotten into chatgpt and it gave me a revised version of the code with double quotes on the command and file path and using the \copy meta command 

**Error:**

```

C:\Users\Sergio Ramos>psql -d analysis -U postgres -c 'COPY FROM STDIN WITH (FORMAT CSV, HEADER);'< "C:\Users\...\practical-sql-2-main\Chapter_10\state_regions.csv"
psql: warning: extra command-line argument "FROM" ignored
psql: warning: extra command-line argument "STDIN" ignored
psql: warning: extra command-line argument "WITH" ignored
psql: warning: extra command-line argument "(FORMAT" ignored
psql: warning: extra command-line argument "CSV," ignored
psql: warning: extra command-line argument "HEADER);'" ignored
Password for user postgres:
ERROR:  unterminated quoted string at or near "'COPY"
LINE 1: 'COPY

```

Its possible I overlooked a typo or its some system difference. I am running a Windows 10 and also have an installation of Anaconda running so maybe that has something to do with it?

I got a weird error when running the .shp file import too where I got stuck in some infinite error loop haha 

But I did still learn a ton from the chapter ! Super helpful

**Comment by anthonydb** [comment]
I think I see the issue. On macOS, you can enclose the `COPY FROM STDIN  ...` portion of the statement with either single or double quotes. On Windows, only double quotes work. 

Double quotes is what I have in the code file for Chapter 18, so if you copy from there you're good on either platform. But in the text of the book I use single quotes.

**Comment by 0sergio-hash** [comment]
Makes sense ! Thank you so much for looking into it
