### ISSUE TITLE
Chapter 1:  Stack Builder Installation Question

### ISSUE THREAD

**Issue by amutabanna** [anthonydb/practical-sql-2#29]
My operating system is Windows 11.

I have not yet finished installing PostgreSQL and pgAdmin as there are discrepancies between the Stack Builder prompts I am seeing and the instructions in the book, specifically at step #10 under Windows Installation on page 5. After Stack Builder launched, I clicked next as step #9 specified, but after that, there was no Spatial Extensions menu or EDB Language Pack available to select.

The version of PostgreSQL I downloaded according to EDB was Version 17.RC1.

Everything from GitHub was installed as directed by the book.

Issue: Chapter 1, page 5, step 10.

![Screenshot 2024-09-21 021524](https://github.com/user-attachments/assets/c82e79c8-350a-43a6-8e42-13a5c40185f8)
![Screenshot 2024-09-21 021653](https://github.com/user-attachments/assets/76c6fea9-6615-4623-94f9-27397c5d8ae8)

**Comment by anthonydb** [comment]
If you installed the release candidate of version 17, uninstall it and choose version 16.4 instead.

<img width="217" alt="Screenshot 2024-09-21 at 6 00 36 AM" src="https://github.com/user-attachments/assets/0dcaf49e-1637-4c81-9ae9-916a58ea4742">

**Comment by amutabanna** [comment]
Thank you!
