### ISSUE TITLE
Exercise 5-1: Answer Incorrect

### ISSUE THREAD

**Issue by silverspade-gh** [anthonydb/practical-sql-2#31]
Having trouble with data, code, or exercises in Practical SQL, 2nd Edition? I'm glad to help. Please answer these questions, and I'll typically reply within one to two business days.

Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

### General
Please answer all of these as they're essential for troubleshooting.

### Issue or Question

**Chapter, page and code listing number:**
Page 75, Chapter 5, Exercise 1

**Describe the issue or your question:**
-- 1. Write a WITH statement to include with COPY to handle the import of an
-- imaginary text file whose first couple of rows look like this:

id:movie:actor
50:#Mission: Impossible#:Tom Cruise

**The answer below is incorrect because it uses FORMAT CSV when the question states that it's a text file.

-- Answer: The WITH statement will need the options seen here:

COPY actors
FROM 'C:\YourDirectory\movies.txt'
WITH (FORMAT CSV, HEADER, DELIMITER ':', QUOTE '#');

Shouldn't it be FORMAT TEXT?

**Comment by anthonydb** [comment]
@silverspade-gh 

Hi, thanks for asking. No, even though the filename has a `.txt` extension, we have to use `CSV` here because we are specifying a `QUOTE` option. `QUOTE` is only available with `FORMAT CSV`

See the PostgreSQL docs at:
https://www.postgresql.org/docs/current/sql-copy.html

**Comment by silverspade-gh** [comment]
Thank you for the reply and documentation. @anthonydb
