### ISSUE TITLE
Some errata for 2nd Edition

### ISSUE THREAD

**Issue by TeeDDub** [anthonydb/practical-sql-2#4]
Hi. Here's some errata I found while translating! 😁

### Chapter 10
180 page
Description for Listing 10-26.
"The second statement renames the copy we made with Listing 10-24 to the original name of the table"
=> "The second statement renames the copy we made with Listing 10-25 to the original name of the table"

### Chapter 12
214 page
Link for data dictionary https://www.nyc.gov/html/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf is unavailable.
New location is https://www1.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf

### Chapter 14
267 page
Above Listing 14-18, It says "It's pipe-delimited and uses an ampersand for quoting." but Listing 14-18 uses @ for quoting.

**Comment by anthonydb** [comment]
Thank you, @TeeDDub! I have updated the FAQ via https://github.com/anthonydb/practical-sql-2/commit/f1739f1e2b2d90564551eaccc74df8458d700dc5
